# Generated by Django 4.2.2 on 2023-07-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archieve', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ayada',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم العيادة'),
        ),
    ]
