# Generated by Django 4.2.2 on 2023-07-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archieve', '0002_alter_ayada_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
